### PR TITLE
Set TLS version to 1.2 so this will work with current server settings.

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
Trying to play with this repo against current MilMove I ran into an issue with the TLS versions which are now more strict on the server side.

### CODE REVIEW

**Review by mr337 — CHANGES_REQUESTED** [review]
Are the precommit hook settings needed to be more strictk on the Nom side?

**Comment by chrisgilmerproj** [comment]
> Are the precommit hook settings needed to be more strictk on the Nom side?

I can't run pre-commit using my version of golang with the old versions of these pre-commit libraries. There's a conflict that doesn't allow it to work.

**Comment by mr337** [comment]
> > Are the precommit hook settings needed to be more strictk on the Nom side?
> 
> I can't run pre-commit using my version of golang with the old versions of these pre-commit libraries. There's a conflict that doesn't allow it to work.

Ahhh ok!

**Review by mr337 — APPROVED** [review]
LGTM 🚢

**Pull request merged**
